In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
a=np.arange(10,100)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [12]:
b=np.flip(a,0)
print(b)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
c=a.reshape(3,30)
print(c)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
  64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
  94 95 96 97 98 99]]


In [19]:
d=[1,2,9,0,0,1,4,0]
for i in np.arange(len(d)):
    if d[i] !=0:
        print(i)

0
1
2
5
6


In [20]:
e=np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
f = np.random.uniform(-1,1,50)
print(f)
print(f.mean())

[-0.08320085  0.0527128   0.6203803   0.12224947  0.45956249  0.40631313
 -0.79534297  0.92046684 -0.99043306  0.68344301  0.88712155 -0.91170298
  0.79450399 -0.78126443  0.0198853   0.32132675 -0.37738743  0.2328061
  0.70404811 -0.81713259 -0.91729351 -0.96492361 -0.75697094  0.05434206
 -0.33198805  0.62890509  0.89448118 -0.07290724 -0.84837069 -0.91202855
 -0.4215639  -0.54926464 -0.21294414 -0.38075298 -0.74656919 -0.1199902
  0.85013195 -0.08493124  0.84141422 -0.82797498  0.69070742  0.72704631
 -0.03403817  0.6174609  -0.62360332 -0.1233209   0.9806064  -0.73977442
  0.22409273  0.57852738]
-0.022262790188912494


In [23]:
g=np.array([[0,0,0,0,0],[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,4,0]])
print(g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
A=4*np.random.rand(5,3)
B=5*np.random.rand(3,4)
print(A)
print(B)
C=np.matmul(A,B)
print(C)

[[1.08144161 2.96748547 1.96687528]
 [0.16435983 1.50197603 2.5141169 ]
 [1.86394696 1.46557212 2.6622827 ]
 [1.14248251 2.78132529 0.80387274]
 [1.64830154 2.62767343 2.63966704]]
[[4.28441234 3.92284029 3.42588362 0.8969896 ]
 [1.56819324 4.22452475 3.85013524 1.25162982]
 [3.98933817 0.50927751 2.07621264 0.09847979]]
[[17.13346307 17.78022388 19.21376478  4.87793265]
 [13.08923643  8.27027547 11.56572975  2.27493674]
 [20.90496366 14.85915268 17.55578124  3.76847585]
 [12.46344188 16.64094827 16.29150137  4.58514983]
 [21.71322762 18.91101819 21.24429736  5.02733761]]


In [47]:
print(np.floor(C))
D=np.zeros(20).reshape(5,4)
for i in np.arange(5):
    for j in np.arange(4):
        D[i,j]=np.floor(C[i,j])
print(D)
        

[[17. 17. 19.  4.]
 [13.  8. 11.  2.]
 [20. 14. 17.  3.]
 [12. 16. 16.  4.]
 [21. 18. 21.  5.]]
[[17. 17. 19.  4.]
 [13.  8. 11.  2.]
 [20. 14. 17.  3.]
 [12. 16. 16.  4.]
 [21. 18. 21.  5.]]


In [49]:
h=np.random.rand(25)
print(h)
print(np.sort(h))

[0.05874841 0.81268518 0.487567   0.8319505  0.43983698 0.0997448
 0.03317389 0.90071564 0.7493842  0.40996049 0.38788723 0.33852555
 0.25189858 0.97702455 0.04788172 0.23951405 0.43730337 0.39617605
 0.32774433 0.66245222 0.98411713 0.32523204 0.98155568 0.96534255
 0.47069086]
[0.03317389 0.04788172 0.05874841 0.0997448  0.23951405 0.25189858
 0.32523204 0.32774433 0.33852555 0.38788723 0.39617605 0.40996049
 0.43730337 0.43983698 0.47069086 0.487567   0.66245222 0.7493842
 0.81268518 0.8319505  0.90071564 0.96534255 0.97702455 0.98155568
 0.98411713]


In [58]:
E=np.random.rand(14).reshape(7,2)
print(E)
for i in np.arange(7):
    rho = np.sqrt(E[i,0]**2 + E[i,1]**2)
    phi = np.arctan2(E[i,1], E[i,0])
    print("al ",i+1,"-lea punt de coordonate polare",rho,"si",phi)

[[0.87790145 0.33147239]
 [0.96278781 0.10175489]
 [0.143861   0.29632426]
 [0.8184449  0.99732988]
 [0.97368619 0.56781734]
 [0.11122299 0.11886343]
 [0.34929813 0.91137079]]
al  1 -lea punt de coordonate polare 0.9383948549312007 si 0.3610250413281898
al  2 -lea punt de coordonate polare 0.9681500047233123 si 0.1052968730046119
al  3 -lea punt de coordonate polare 0.32939953836345287 si 1.118827953685656
al  4 -lea punt de coordonate polare 1.290162368093494 si 0.8835984483435695
al  5 -lea punt de coordonate polare 1.1271563042835548 si 0.5279470310550153
al  6 -lea punt de coordonate polare 0.16278534518100538 si 0.8185928345686595
al  7 -lea punt de coordonate polare 0.9760153126405751 si 1.2047978559883883


In [64]:
F=np.random.rand(100).reshape(10,10)
x=float(np.random.rand(1))
m=abs(x-F[0,0])
n=F[0,0]
for i in np.arange(10):
    for j in np.arange(10):
        if abs(x-F[i,j])<m:
            m=abs(x-F[i,j])
            n=F[i,j]
print("cel mai apropiat numara de valoarea ",x," este ",n)

cel mai apropiat numara de valoarea  0.8610672816261883  este  0.8630966993087468
